# Generated by Django 5.2.3 on 2025-06-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
